name: cc-mk-include
lang: unknown
lang_version: unknown
git:
  enable: true

  repo_name: confluentinc/cc-mk-include
semaphore:
  enable: true
  pipeline_enable: false
  triggers:
  - tags
  - branches
  - pull_requests
  - forked_pull_requests
  branches:
  - master
  - /^v\d+\.\d+\.x$/
