project_name: confluent-cloud-secrets-engine

release:
  prerelease: auto
  name_template: "confluent-cloud-secrets-engine v{{.Version}}"

builds:
  - id: macos
    binary: confluent-cloud-secrets-engine
    ldflags:
      - -s -w -X github.com/confluentinc/confluent-cloud-secrets-engine/internal/build.Version={{.Version}} -X github.com/confluentinc/confluent-cloud-secrets-engine/internal/build.Date={{time "2006-01-02"}}
    goos: [darwin]
    goarch: [amd64, arm64]

archives:
  - id: macos
    builds: [macos]
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    wrap_in_directory: "true"
    format: tar.gz

checksum:
  name_template: "checksums.txt"
  algorithm: sha256