name: confluent-cloud-secrets-engine
lang: go
lang_version: 1.23.8
git:
  enable: true
github:
  repo_name: confluentinc/confluent-cloud-secrets-engine
  enable: true
semaphore:
  enable: true
make:
  enable: true
  update_makefile: false
  enable_updates: true
