name: pie-cc-hashicorp-vault-plugin
lang: go
lang_version: ${.go-version}
git:
  enable: true
github:
  enable: true
semaphore:
  enable: true
make:
  enable: true
  update_makefile: false
  enable_updates: true
